### ISSUE TITLE
`ramble python` command

### ISSUE THREAD

**Issue by becker33** [GoogleCloudPlatform/ramble#360]
### Summary

Spack has a functionality to run a python interpreter with access to the Spack internals, called `spack python`. There is a corrosponding `spack-python` executable to make it runnable in `#!` scripts.

### Rationale

This will allow advanced users to create one-off utilities for their users and/or explore the internals to improve their understanding of ramble.

### Description

Copy and modify the `spack python` command from Spack to adapt it to Ramble's needs.

### Additional information

Not available yet as of
```
$ ./bin/ramble -V
0.3.0 (605291fac1684309b857cefba9f508bb43c44b18)
```

### General information

- [X] I have run `ramble --version` and reported the version of Ramble
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by rfbgo** [comment]
Can you give an example concrete use case for this?

**Comment by becker33** [comment]
For example, if I want to enforce additional constraints beyond what ramble enforces on the workspaces for my users. I could write a `ramble python` script that accesses the workspace, checks for the invariants I want, errors out if appropriate, and then continues to setup the workspace. The invariants may be things that are much easier to check in code than in yaml.

Another example would be to check which spack packages are defined by a particular config file. I could obviously write a pure yaml script for it, but that won't integrate as seemlessly with changes in the config system.

I think this is something like 10 minutes of developer time to implement, I just can't contribute it myself because my organization cannot figure out how to let me sign the CLA yet.
