### ISSUE TITLE
documentation not working

### ISSUE THREAD

**Issue by shahzebsiddiqui** [GoogleCloudPlatform/ramble#62]
### Steps to reproduce

https://github.com/GoogleCloudPlatform/ramble/blob/develop/docs/Getting_Started.md

![Screen Shot 2023-03-02 at 11 05 32 AM](https://user-images.githubusercontent.com/12942230/222483753-6df45855-3cd1-496e-b79a-92d19fbdcd2c.png)

I was reading the README https://github.com/GoogleCloudPlatform/ramble#documentation and the link was broken

### Information on your system

N/A

### General information

- [X] I have run `ramble debug report` and reported the version of Ramble/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by shahzebsiddiqui** [comment]
It's still broken u might want to check again.

**Comment by douglasjacobsen** [comment]
@shahzebsiddiqui Thanks. Which branch are you using? For me, it works on develop, but not on main (so it'll be fixed on main the next time we do a release).
